baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-GB
name: 'Ability Network'
primary: true
siteGroup: a82a3f16-e7f7-4af6-9ae7-a60290ab4589 # Ability Network 
sortOrder: 1
