field: 2c263ea2-c9e3-4c8d-92d0-a28bb8f2a10a # Contact Us
fieldLayouts:
  9b856823-882c-4a34-af33-21e6034f9e3c:
    tabs:
      -
        elements:
          -
            fieldUid: d76fa8c2-725a-4a58-a1ff-4670a61387cc # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  d76fa8c2-725a-4a58-a1ff-4670a61387cc: # Address
    contentColumnType: text
    fieldGroup: null
    handle: address
    instructions: ''
    name: Address
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: address
name: Address
sortOrder: 3
