field: cf6a1d01-0306-47fb-bc42-46a0217151f0 # disabilityservice
fieldLayouts:
  592bee1f-95a4-4416-8859-a12e39b6680d:
    tabs:
      -
        elements:
          -
            fieldUid: 78da2f88-b585-44e2-89ee-9383fb061a14 # disability title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e04a4fc5-cc66-4234-9f9a-d7dfe0ff2788 # disability description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  78da2f88-b585-44e2-89ee-9383fb061a14: # disability title
    contentColumnType: text
    fieldGroup: null
    handle: disabilityTitle
    instructions: ''
    name: 'disability title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e04a4fc5-cc66-4234-9f9a-d7dfe0ff2788: # disability description
    contentColumnType: text
    fieldGroup: null
    handle: disabilityDescription
    instructions: ''
    name: 'disability description'
    searchable: false
    settings:
      columnType: text
      initJs: null
      purifierConfig: ''
      purifyHtml: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: basicinfo
name: basicinfo
sortOrder: 1
