field: 8194d89f-441d-416f-8edd-25ef062416e4 # Footer Logos
fieldLayouts:
  d2808ccb-ed47-496e-8fb3-0406eaa0597a:
    tabs:
      -
        elements:
          -
            fieldUid: bdb81143-038b-4e8a-9a12-7654c8f727c0 # Footer Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ff1ce668-1344-4f83-86c7-1676bef3e3cb # External Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  bdb81143-038b-4e8a-9a12-7654c8f727c0: # Footer Logo
    contentColumnType: string
    fieldGroup: null
    handle: footerLogo
    instructions: ''
    name: 'Footer Logo'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:9c85c264-0d55-45a0-85a7-92df5c20c108' # images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9c85c264-0d55-45a0-85a7-92df5c20c108' # images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ff1ce668-1344-4f83-86c7-1676bef3e3cb: # External Url
    contentColumnType: text
    fieldGroup: null
    handle: externalUrl
    instructions: ''
    name: 'External Url'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: footerIcon
name: 'Footer Icon'
sortOrder: 1
