field: 967a24f7-1f88-4f72-b80a-b8bbcbc6db9c # News
fieldLayouts:
  cd01764c-71dd-4d2c-baa3-97328fead903:
    tabs:
      -
        elements:
          -
            fieldUid: a593f420-cccf-4ad1-8f84-3293e9bbf099 # Newsletter Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8e2bcea8-7c2f-419e-b571-b5b27e9af17d # Newsletter Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8e2bcea8-7c2f-419e-b571-b5b27e9af17d: # Newsletter Url
    contentColumnType: text
    fieldGroup: null
    handle: newsletterUrl
    instructions: ''
    name: 'Newsletter Url'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a593f420-cccf-4ad1-8f84-3293e9bbf099: # Newsletter Title
    contentColumnType: text
    fieldGroup: null
    handle: newsletterTitle
    instructions: ''
    name: 'Newsletter Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: previousNewsletter
name: 'Previous Newsletter'
sortOrder: 2
