field: 9dfef8a6-85cc-425c-b286-3240e672088d # Home Slider
fieldLayouts:
  dd1a6791-2c61-4cf0-ae95-1dc06ade2bcb:
    tabs:
      -
        elements:
          -
            fieldUid: ea54183b-6896-43b2-a89b-18bf54e3bc01 # Slider Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e8636a2f-e621-41d9-a9f7-1d37ec7a1eff # sliderimage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3af21b41-30e8-4cd0-aa40-4e42ebeb6952 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0354659a-15ff-4aac-8bf6-1f678e120daf # Button Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3af21b41-30e8-4cd0-aa40-4e42ebeb6952: # Button Text
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  0354659a-15ff-4aac-8bf6-1f678e120daf: # Button Url
    contentColumnType: text
    fieldGroup: null
    handle: buttonUrl
    instructions: ''
    name: 'Button Url'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e8636a2f-e621-41d9-a9f7-1d37ec7a1eff: # sliderimage
    contentColumnType: string
    fieldGroup: null
    handle: sliderimage
    instructions: ''
    name: sliderimage
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:9c85c264-0d55-45a0-85a7-92df5c20c108' # images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9c85c264-0d55-45a0-85a7-92df5c20c108' # images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ea54183b-6896-43b2-a89b-18bf54e3bc01: # Slider Content
    contentColumnType: text
    fieldGroup: null
    handle: sliderContent
    instructions: ''
    name: 'Slider Content'
    searchable: false
    settings:
      columnType: text
      initJs: null
      purifierConfig: ''
      purifyHtml: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: slider
name: slider
sortOrder: 1
