field: 87edd3bd-c454-4a7b-95e7-42be25adc750 # Welcome To Country
fieldLayouts:
  ab4b1485-94a8-4667-be08-029495cac2a2:
    tabs:
      -
        elements:
          -
            fieldUid: 57a4acdb-e238-4bf4-a3dc-5a39b3ed2d9d # Testimonial Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2eff2f65-4229-42f4-9553-5671662b694e # Rating
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7be3bd5b-f684-425e-9811-0eb87b7c0583 # Author Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2eff2f65-4229-42f4-9553-5671662b694e: # Rating
    contentColumnType: text
    fieldGroup: null
    handle: rating
    instructions: ''
    name: Rating
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7be3bd5b-f684-425e-9811-0eb87b7c0583: # Author Name
    contentColumnType: text
    fieldGroup: null
    handle: authorName
    instructions: ''
    name: 'Author Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  57a4acdb-e238-4bf4-a3dc-5a39b3ed2d9d: # Testimonial Description
    contentColumnType: text
    fieldGroup: null
    handle: testimonialDescription
    instructions: ''
    name: 'Testimonial Description'
    searchable: false
    settings:
      columnType: text
      initJs: null
      purifierConfig: ''
      purifyHtml: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: testimonials
name: Testimonials
sortOrder: 2
