fieldLayouts:
  b389f2ab-7b97-4f0c-a431-ce0ac25c81ed:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: cf6a1d01-0306-47fb-bc42-46a0217151f0 # disabilityservice
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: agedCareServices
hasTitleField: true
name: 'Aged Care Services'
section: d074a546-9680-423b-89db-a2f1349ac528 # Aged Care Services
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
