contentColumnType: string
fieldGroup: 3ccf1e97-e678-4106-a9e1-bb71dac0ccb9 # Footer
handle: agedCareServiceLink
instructions: ''
name: 'Aged Care Service Link'
searchable: false
settings:
  contentTable: '{{%matrixcontent_agedcareservicelink}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
