contentColumnType: string
fieldGroup: dc29ed7e-d549-4b85-b732-051b148728d0 # Home Page
handle: homeslider
instructions: ''
name: 'Home Slider'
searchable: false
settings:
  contentTable: '{{%matrixcontent_homeslider}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
