contentColumnType: string
fieldGroup: a8b1ea0d-5b09-4dc2-b4bc-151c7c329721 # Common
handle: pageLink
instructions: ''
name: 'Page Link'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagelink}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
