contentColumnType: text
fieldGroup: a8b1ea0d-5b09-4dc2-b4bc-151c7c329721 # Common
handle: servicecontent
instructions: ''
name: servicecontent
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '8'
  multiline: '1'
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
