contentColumnType: string
fieldGroup: 3ccf1e97-e678-4106-a9e1-bb71dac0ccb9 # Footer
handle: socialMediaIcons
instructions: ''
name: 'Social Media Icons'
searchable: false
settings:
  contentTable: '{{%matrixcontent_socialmediaicons}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
