contentColumnType: string
fieldGroup: dc29ed7e-d549-4b85-b732-051b148728d0 # Home Page
handle: welcomeToCountry
instructions: ''
name: 'Welcome To Country'
searchable: false
settings:
  contentTable: '{{%matrixcontent_welcometocountry}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
