enableVersioning: true
handle: agedCareServices
name: 'Aged Care Services'
propagationMethod: all
siteSettings:
  df7fc7bc-9d93-47ae-bb05-0586de63ab70: # Ability Network
    enabledByDefault: true
    hasUrls: true
    template: _singles/agedcare-service
    uriFormat: '{slug}'
type: single
