enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  df7fc7bc-9d93-47ae-bb05-0586de63ab70: # Ability Network
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
