enableVersioning: true
handle: ourPeople
name: 'Our People'
propagationMethod: all
siteSettings:
  df7fc7bc-9d93-47ae-bb05-0586de63ab70: # Ability Network
    enabledByDefault: true
    hasUrls: true
    template: _singles/our-people
    uriFormat: '{slug}'
type: single
