enableVersioning: true
handle: whereWeService
name: 'Where we Service'
propagationMethod: all
siteSettings:
  df7fc7bc-9d93-47ae-bb05-0586de63ab70: # Ability Network
    enabledByDefault: true
    hasUrls: true
    template: _singles/where-we-service
    uriFormat: where-we-service
type: single
