fieldLayouts:
  70540b92-c527-451d-8c66-123e246a2e07:
    tabs:
      -
        elements:
          -
            fieldUid: 9d9c5b46-fa74-4076-983f-49038a678bed # External Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Useful Links'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 0da7c9a9-9f45-4912-acae-526b7b4ed224 # About Us Internal Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 88556077-d7fc-4c86-b890-9dba5623e91c # About Us External Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'About Us'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 0ae5ba23-3c57-479d-a905-8da033ba3f45 # Social Media Icons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Social
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 8194d89f-441d-416f-8edd-25ef062416e4 # Footer Logos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Footer Logos'
        sortOrder: 4
handle: footer
name: Footer
sortOrder: 2
